### ISSUE TITLE
깃 충돌

### ISSUE THREAD

**Issue by trueS2** [100-hours-a-week/discussions#8]
# 사용방법

feature 브랜치에서 머지, 리베이스가 되지 않습니다.
안되는 이유를 모르겠습니다.

현재 상황
develop 브랜치는 최신 상태
feat 브랜치는 최신 상태가 아님

문제
develop과 동일하게 feat도 최신 상태로 업데이트를 하고 싶은데 오류 발생

----
![image](https://github.com/user-attachments/assets/f4a9a97a-a135-42b7-9a5c-9ea71ae1ed55)

_Originally posted by @ej31 in https://github.com/100-hours-a-week/discussions/discussions/2_

**Comment by trueS2** [comment]
히힛 해결했습니다

**Comment by ej31** [comment]
앞으로는 이 [링크](https://github.com/orgs/100-hours-a-week/discussions?discussions_q=) 로 올려주세요~~
